# Environment Settings
env:
  observation_config: "/home/cirs_alaa/repositories/stonefish_rl/include/observations/ds_obser_v2_config.json"
  action_config: "/home/cirs_alaa/repositories/stonefish_rl/include/observations/ds_action_config.json"
  instances: 20
  base_port: 5555
  episode_duration: 60
  rl_observation_freq: 5


sim:
  scene_path: "/home/cirs_alaa/repositories/stonefish_rl/Resources/girona_ds/scenarios/girona500_docking_sim_pool.scn"
  resources_path: "/home/cirs_alaa/repositories/stonefish_rl/"
  graphical_interface: False
  evaluation_graphical_interface: True
  resolution: 400
  realtime: False
  current: False

# This maps the forces (x,y,z,roll,pitch,yaw) of the thusters setpoints
# It changes the action space size, to match the forces, 
# The RL output forces, then the code convert forces to setpoint, and Simulation recieves Setpoints
action: 
  force_6Dof: True
  tcm: [[-1,-1,0,0,0],
        [0,0,1,0,0],
        [0,0,0,-1,-1],
        [0,0,0,0,0],
        [0,0,0,1,-1],
        [-1,1,0,0,0]]


# Model for Evaluation
# If pretrained is set to True, Model path should be specified 
model:
  pretrained: False
  model_path: "PPO_PPO_O11_A6_20260226_200005" 
  algorithm: "SAC"

  # comment param
  policy: "MlpPolicy"
  learning_rate: 0.0005
  buffer_size: 500000
  batch_size: 1024

  # SAC param
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  learning_starts: 1000

  # PPO PARAM
  n_steps: 2048
  ent_coef: 0.01
  clip_range: 0.2

  # TD3 param , TO DO , NOT WORKING
  policy_delay: 2


# Neural Network Architecture if needed 
policy:
  custom_policy: False
  net_arch:
    pi: [256, 256]
    qf: [256, 256]
  activation_fn: "relu" # map this string to th.nn.ReLU in Python

# Training Settings
train:
  total_timesteps: 2000_000
  reset_num_timesteps: False
  eval_freq: 2000
  save_path: "default"
  save_name: "PPO_O11_A6"
  warm_start_path: "PPO_"
  weights_only: True

log: 
  enable_wandb: True
  project_name: "stonefish_docking"
  run_name: "default"
  tags: ["PPO", "docking", "stonefish"]
  log_dir: "./logs/"
